name: cool_dropdown
description: Customizable cool dropdown UI You can customize selected item, BoxDecoration of the dropdownBox, and dropdown input.
version: 2.1.0
homepage: https://github.com/joo6077/cool_dropdown

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

