name: cool_dropdown
description: Customizable cool dropdown UI You can customize selected item, BoxDecoration of the dropdownBox, and dropdown input.
version: 2.6.2
homepage: https://github.com/joo6077/cool_dropdown

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
